export const GET_BOWLS_START = 'GET_BOWLS_START'
export const GET_BOWLS_SUCCESS = 'GET_BOWLS_SUCCESS'
export const GET_BOWLS_FAIL = 'GET_BOWLS_FAIL'

export const GET_SIZES_START = 'GET_SIZES_START'
export const GET_SIZES_SUCCESS = 'GET_SIZES_SUCCESS'
export const GET_SIZES_FAIL = 'GET_SIZES_FAIL'

export const GET_BASES_START = 'GET_BASES_START'
export const GET_BASES_SUCCESS = 'GET_BASES_SUCCESS'
export const GET_BASES_FAIL = 'GET_BASES_FAIL'

export const GET_SAUCES_START = 'GET_SAUCES_START'
export const GET_SAUCES_SUCCESS = 'GET_SAUCES_SUCCESS'
export const GET_SAUCES_FAIL = 'GET_SAUCES_FAIL'

export const GET_INGREDIENTS_START = 'GET_INGREDIENTS_START'
export const GET_INGREDIENTS_SUCCESS = 'GET_INGREDIENTS_SUCCESS'
export const GET_INGREDIENTS_FAIL = 'GET_INGREDIENTS_FAIL'

export const GET_EXTRA_INGREDIENTS_START = 'GET_EXTRA_INGREDIENTS_START'
export const GET_EXTRA_INGREDIENTS_SUCCESS = 'GET_EXTRA_INGREDIENTS_SUCCESS'
export const GET_EXTRA_INGREDIENTS_FAIL = 'GET_EXTRA_INGREDIENTS_FAIL'

export const NEXT_STEP = 'NEXT_STEP'
export const BACK_STEP = 'BACK_STEP'

export const ADD_BOWL = 'ADD_BOWL'
export const ADD_SIZE = 'ADD_SIZE'
export const ADD_BASE = 'ADD_BASE'
export const ADD_SAUCE = 'ADD_SAUCE'
export const ADD_INGREDIENT = 'ADD_INGREDIENT'
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT'
export const ADD_EXTRA_INGREDIENT = 'ADD_EXTRA_INGREDIENT'
export const REMOVE_EXTRA_INGREDIENT = 'REMOVE_EXTRA_INGREDIENT'

export const RESET_ORDER = 'RESET_ORDER'
export const REMOVE_ORDER = 'REMOVE_ORDER'

export const ADD_QUANTITY = 'ADD_QUANTITY'

export const SAVE_ORDER = 'SAVE_ORDER'